Repository jenkinsci/accurev-plugin, pull requests merged in 2019-05, with the labels that each got.

#68 Fix pipeline handling of wspaceORreftree
  src/main/java/hudson/plugins/accurev/AccurevSCM.java
  src/test/java/hudson/plugins/accurev/AccurevSCMTest.java
Labels: bugfix

#67 Add option to populate the sub-path only, without creating the directory tree
  src/main/java/hudson/plugins/accurev/AccurevSCM.java
  src/main/java/hudson/plugins/accurev/cmd/PopulateCmd.java
  src/main/resources/hudson/plugins/accurev/AccurevSCM/config.jelly
  src/main/webapp/help/project/subpathonly.html
Labels: feature

#70 [JENKINS-41102] fix Job "Changes" do not match "Filter for Poll SCM"
  src/main/java/hudson/plugins/accurev/CheckForChanges.java
  src/main/java/hudson/plugins/accurev/ParseChangeLog.java
  src/main/java/hudson/plugins/accurev/delegates/ReftreeDelegate.java
  src/main/java/hudson/plugins/accurev/delegates/SnapshotDelegate.java
  src/main/java/hudson/plugins/accurev/delegates/StreamDelegate.java
  src/main/java/hudson/plugins/accurev/delegates/WorkspaceDelegate.java
Labels: bugfix

#71 Update parent POM
  pom.xml
Labels: chore
