Repository jenkinsci/accurev-plugin, pull requests merged in 2019-10, with the labels that each got.

#73 Update help message for sub path
  src/main/webapp/help/project/subpath.html
Labels: skip-changelog

#80 switch url to point to github as wiki.jenkins.io is made read-only
  pom.xml
Labels: chore

#83 MicroFocus contributed -Method Parameter interchanged in Hist command
  src/main/java/hudson/plugins/accurev/CheckForChanges.java
Labels: bugfix
